version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: rollup
    versions:
    - 2.38.4
    - 2.39.0
    - 2.42.0
    - 2.43.1
    - 2.44.0
  - dependency-name: vue
    versions:
    - 3.0.5
    - 3.0.7
    - 3.0.9
    - 3.0.9
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.5
    - 3.0.7
    - 3.0.9
  - dependency-name: "@babel/types"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.13
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
  - dependency-name: husky
    versions:
    - 5.1.0
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.4.0
  - dependency-name: "@types/estree"
    versions:
    - 0.0.46
  - dependency-name: ts-jest
    versions:
    - 25.5.1
