name: Bug report
description: Create a report to help us improve
labels: ['bug']
title: 'Bug: '
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project! We appreciate bugs filed and PRs submitted!

        Please use a template below to create a minimal reproduction
        👉 https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts

        For test-utils v1 and Vue v2, please report at:
        👉 https://github.com/vuejs/vue-test-utils
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      placeholder: https://stackblitz.com/...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: Environment
      description: Output of  `npx envinfo --system --npmPackages vue,@vue/test-utils,vitest,jest`.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
